Repository AllDaySideProject/Backend, pull requests merged in 2025-08, with the labels that each got.

#10 ✨ feat : 특정 메뉴를 파는 가게 조회 API 구현
  src/main/java/com/example/Centralthon/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuService.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuServiceImpl.java
  src/main/java/com/example/Centralthon/domain/menu/web/controller/MenuController.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/StoresByMenuRes.java
  src/main/java/com/example/Centralthon/global/util/geo/GeoUtils.java
Labels: ✨feature

#17 ✨ feat : 메뉴 상세 조회 API 구현
  build.gradle
  src/main/java/com/example/Centralthon/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/example/Centralthon/domain/menu/exception/MenuNotFoundException.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuService.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuServiceImpl.java
  src/main/java/com/example/Centralthon/domain/menu/web/controller/MenuController.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/MenuDetailsRes.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/MenuIdsReq.java
  src/main/java/com/example/Centralthon/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/Centralthon/global/response/SuccessResponse.java
Labels: ✨feature

#22 ✨ feat: 주문 생성 API 개발
  src/main/java/com/example/Centralthon/domain/order/entity/Order.java
  src/main/java/com/example/Centralthon/domain/order/entity/OrderItem.java
  src/main/java/com/example/Centralthon/domain/order/exception/CodeNotCreatedException.java
  src/main/java/com/example/Centralthon/domain/order/exception/OrderErrorCode.java
  src/main/java/com/example/Centralthon/domain/order/repository/OrderItemRepository.java
  src/main/java/com/example/Centralthon/domain/order/repository/OrderRepository.java
  src/main/java/com/example/Centralthon/domain/order/service/OrderService.java
  src/main/java/com/example/Centralthon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/example/Centralthon/domain/order/web/controller/OrderController.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/OrderItemListReq.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/OrderReq.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/OrderRes.java
Labels: ✨feature

#24 ♻️ refactor: 주문 시, 가게 기본 키를 반환하도록 수정
  src/main/java/com/example/Centralthon/domain/order/service/OrderService.java
  src/main/java/com/example/Centralthon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/example/Centralthon/domain/order/web/controller/OrderController.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/CreateOrderReq.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/CreateOrderRes.java
  src/main/java/com/example/Centralthon/domain/order/web/dto/OrderRes.java
Labels: :recycle: refactor

#28 ✨ feat : 가게 판매 메뉴 목록 조회 API 개발
  src/main/java/com/example/Centralthon/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/MenuDetailsRes.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/MenuItemRes.java
  src/main/java/com/example/Centralthon/domain/store/exception/StoreErrorCode.java
  src/main/java/com/example/Centralthon/domain/store/exception/StoreNotFoundException.java
  src/main/java/com/example/Centralthon/domain/store/service/StoreService.java
  src/main/java/com/example/Centralthon/domain/store/service/StoreServiceImpl.java
  src/main/java/com/example/Centralthon/domain/store/web/controller/StoreController.java
  src/main/java/com/example/Centralthon/domain/store/web/dto/StoreMenusRes.java
Labels: ✨ feature

#32 🔧 chore: 스웨거 세팅
  build.gradle
  src/main/java/com/example/Centralthon/domain/order/web/controller/OrderApi.java
  src/main/java/com/example/Centralthon/domain/order/web/controller/OrderController.java
  src/main/java/com/example/Centralthon/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: 🔧 settings

#40 🐛 fix : 원가, 할인율 전달 수정
  src/main/java/com/example/Centralthon/domain/menu/web/dto/StoresByMenuRes.java
Labels: 🐛 fix

#41 ✨ feat: Fast API와 연동
  src/main/java/com/example/Centralthon/domain/menu/entity/enums/Concept.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuService.java
  src/main/java/com/example/Centralthon/domain/menu/service/MenuServiceImpl.java
  src/main/java/com/example/Centralthon/domain/menu/web/controller/MenuApi.java
  src/main/java/com/example/Centralthon/domain/menu/web/controller/MenuController.java
  src/main/java/com/example/Centralthon/domain/menu/web/dto/GetRecommendedMenusReq.java
  src/main/java/com/example/Centralthon/global/config/RestTemplateConfig.java
  src/main/java/com/example/Centralthon/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/Centralthon/global/external/ai/client/AiClient.java
  src/main/java/com/example/Centralthon/global/external/ai/service/AiService.java
  src/main/java/com/example/Centralthon/global/external/ai/service/AiServiceImpl.java
  src/main/java/com/example/Centralthon/global/external/ai/web/dto/GetMenusByConceptReq.java
  src/main/java/com/example/Centralthon/global/external/ai/web/dto/GetMenusByConceptRes.java
  src/main/java/com/example/Centralthon/global/external/ai/web/dto/GetMenusByConceptWrapper.java
  src/main/java/com/example/Centralthon/global/external/ai/web/dto/GetTipReq.java
  src/main/java/com/example/Centralthon/global/external/ai/web/dto/GetTipRes.java
  src/main/java/com/example/Centralthon/global/external/exception/AiCommunicationFailedException.java
  src/main/java/com/example/Centralthon/global/external/exception/AiErrorCode.java
  src/main/java/com/example/Centralthon/global/external/response/ExternalResponse.java
Labels: ✨ feature

#44 🐛 fix : 최적 경로 직선 구간 수정
  src/main/java/com/example/Centralthon/domain/route/algo/PathStitcher.java
Labels: 🐛 fix
